version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./php
            dockerfile: dockerfile
        depends_on:
            - db
        volumes:
            - ../:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cicd_tama
            MYSQL_USER: cicd_tama
            MYSQL_PASSWORD: cicd_tama
        ports:
            - "9906:3306"
    composer:
        image: composer:2
        volumes: 
            - ../:/app
        command: install